### ISSUE TITLE
PHP formatting errors

### ISSUE THREAD

**Issue by sherakama** [jbickar/user_list#3]
line="11" column="1" message="Expected 2 space(s) before asterisk; 1 found"

 line="12" column="1" message="Expected 2 space(s) before asterisk; 1 found" 

 line="90" column="69"  message="Concat operator must be surrounded by spaces" 

 line="97" column="25"  message="A cast statement must be followed by a single space" 

 line="123" column="36"  message="Concat operator must be surrounded by spaces" 

 line="136" column="3"  message="Line indented incorrectly; expected 4 spaces, found 2" 

 line="143" column="5"  message="Expected "if (...) {" found "if(...) {\n"" 

 line="145" column="7"  message="Expected "foreach (...) {\n"; found "foreach(...){\n"" 

 line="146" column="9"  message="Inline comments must start with a capital letter" 

 line="146" column="9"  message="Inline comments must end in full-stops, exclamation marks, or question marks" 

 line="156" column="5"  message="Inline comments must end in full-stops, exclamation marks, or question marks" 

 line="163" column="5"  message="Expected "if (...) {\n"; found "if(...) {\n"" 

 line="166" column="5"  message="Expected "if (...) {\n"; found "if(...) {\n"" 

 line="187" column="8"  message="Array closing indentation error, expected 6 spaces but found 7"

 line="190" column="3"  message="Line indented incorrectly; expected 4 spaces, found 2" 

 line="191" column="1"  message="Functions must not contain multiple empty lines in a row; found 2 empty lines"

 line="196" column="1"  message="Files must end in a single new line character"

**Comment by jbickar** [comment]
This is what happens, Larry. This is what happens when you can't use PHPStorm in hidden directories.

**Comment by jbickar** [comment]
This should be fixed with f21e468 but I can't get my CodeSniffer working.
